apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  labels:
    app.kubernetes.io/name: mongodb
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: "13.1.4"  # Replace with the version you want to use
    helm:
      values: |
        image:
          tag: "6.0.6-debian-11-r0"  # Pin to a stable image tag

        auth:
          enabled: true
          existingSecret: mongodb-credentials
          # The key must match the chart's expected key (usually 'mongodb-root-password')
          secretKeys:
            rootPasswordKey: mongodb-root-password

        architecture: standalone

        persistence:
          enabled: true
          size: 8Gi
          storageClass: "standard"  # Replace with your actual StorageClass

        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

        service:
          port: 27017

        metrics:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
