apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: products
    namespace: argocd
spec:
    project: default
    source:
        repoURL: "https://github.com/maxiemoses-eu/agrocd-yaml.git"
        targetRevision: main
        path: chart/products-chart
    destination:
        server: "https://kubernetes.default.svc"
        namespace: products
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true