apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  labels:
    app.kubernetes.io/name: redis
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: "19.4.0"  # Replace with the version you want to use
    helm:
      values: |
        image:
          tag: "7.0.14-debian-11-r0"  # Pin to a stable image tag

        auth:
          enabled: true
          existingSecret: redis-credentials
          secretKeys:
            passwordKey: redis-password

        architecture: standalone

        master:
          persistence:
            enabled: true
            size: 8Gi
            storageClass: "standard"  # Replace with your actual StorageClass
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

        service:
          port: 6379

        metrics:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

