apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
  labels:
    app.kubernetes.io/name: secrets-app
    app.kubernetes.io/part-of: stream-application
spec:
  project: default
  source:
    repoURL: "https://github.com/example-org/stream-configs.git" # replace with your repo
    targetRevision: HEAD
    path: stream-application/secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true